steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/node-web-app-repo/node-web-app', '.']
  
  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/node-web-app-repo/node-web-app']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'node-web-app', 
           '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/node-web-app-repo/node-web-app:latest', 
           '--region', 'us-central1', 
           '--allow-unauthenticated', 
           '--port', '8888']

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/node-web-app-repo/node-web-app:latest'
