name: Build and push Docker image to dockerhub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Check out the repo
      uses: actions/checkout@v4

    # Step 2: Authenticate with Dockerhub
    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Step 3: Build and Push to Dockerhub
    - name: Build and push to dockerhub
      uses: docker/build-push-action@v5
      with:
       context: .
       push: true
       tags: syedwahid/githubaction:latest
